# Generated by Django 3.2.4 on 2021-07-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Post title')),
                ('summary', models.CharField(max_length=255, verbose_name='Summary')),
                ('keywords', models.CharField(max_length=255, verbose_name='SEO Keywords')),
                ('body', models.TextField(verbose_name='Post body')),
                ('published', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=255, unique=True, verbose_name='Slug')),
            ],
        ),
    ]
